### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by willmot** [humanmade/Import-Fixers#1]
Looks solid, only minor things which you might just want to ignore

> https://github.com/humanmade/Import-Fixers/blob/master/hm-import-fixers.php#L82

A bit more docblock explanation here would be useful, took me a minute to work out why calling `get_posts` inside a `while` definition was intentional.

> https://github.com/humanmade/Import-Fixers/blob/master/hm-import-fixers.php#L5

Better to just check `if ( ! class_exists( 'WP_CLI_Command' ) ) {}` here?

> https://github.com/humanmade/Import-Fixers/blob/master/hm-import-fixers.php#L41

`dry_run` defaulting to `true` seems like a more standard approach here.

> https://github.com/humanmade/Import-Fixers/blob/master/hm-import-fixers.php#L46

tabbing

**Comment by paulgibbs** [comment]
Thanks for the feedback, @willmot!

**Comment by willmot** [comment]
👍
